#pragma once

#define EXPERIMENT_SPARSE_CODING 0
#define EXPERIMENT_SINUS_EXAMPLE 1
#define EXPERIMENT_BINH_TEST 2
#define EXPERIMENT_MNIST_VIDEO 3
#define EXPERIMENT_TEXT_PREDICTION 4
#define EXPERIMENT_RNN_BENCHMARK 5
#define EXPERIMENT_AUDIO_GENERATE 6
#define EXPERIMENT_RUNNER 7
#define EXPERIMENT_PONG 8
#define EXPERIMENT_BALANCER 9
#define EXPERIMENT_SEQUENCE_RECALL 10

#define EXPERIMENT_SELECTION EXPERIMENT_BINH_TEST
